### ISSUE TITLE
Health checks failed for all instances

### ISSUE THREAD

**Issue by satheesh3** [emqx/cdk-emqx-cluster#108]
New to this, I was able to deploy the cluster but all the health checks have been failed in load balancer target groups thus cant connect to the cluster.

**Comment by id** [comment]
@satheesh3 this repository is intended for internal use only, when we need to setup a test cluster to run a benchmark. And it wasn't updated for quite a while.

Please do not expect support for this one.

If you need an advice about deployment, one option is to start a discussion on https://github.com/emqx/emqx/discussions.

**Comment by satheesh3** [comment]
Thanks I will check it out
